# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  version "0.10.2"

  on_macos do
    on_intel do
      sha256 "d894071884de53dbe7841c81d51fa54fadc711ea1d80eaf2e65b26cdb252cee3"
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f2ab84205215ff41ffd0a102b29116b7e7e25d5d46fa1c5210db1ad431d1197"
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b9b0190e191aeb0a63d0fa56924d6f633312d10d49de4f64386fc2b7c8cc56d"
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c83de4c287a669cd8cecb49ed83c5fa6bf4c7044b257a6779b3e04c7088fa9a"
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bb"
  desc "CLI to keep Git repositories consistent across machines."
  homepage "https://github.com/niieani/bb-project"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  # No zap stanza required

end
