# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  name "bb"
  desc "CLI to keep Git repositories consistent across machines."
  homepage "https://github.com/niieani/bb-project"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  on_macos do
    on_intel do
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_darwin_amd64.tar.gz"
      sha256 "8d746c267abdb588f3435e0a42ca6b1502f050cbe6913dd03b2b7772fe680045"
    end
    on_arm do
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz"
      sha256 "d345842d8daea24e37058c358e7a97ae18ebbfe0b3bebc88490cf9dedd0924ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_linux_amd64.tar.gz"
      sha256 "2f8465d01fe2e7df4c2fff07067c4d044c761cb05aa909c7e7d824ad63d87d1b"
    end
    on_arm do
      url "https://github.com/niieani/bb-project/releases/download/v#{version}/bb_#{version}_linux_arm64.tar.gz"
      sha256 "79ac8e6ca6f93d527a44f0abc4225aa508e93897ddd761c0715b417e219e50d5"
    end
  end

  # No zap stanza required
end
