# This file is generated by niieani/imagegen release automation. DO NOT EDIT.
cask "imagegen" do
  name "imagegen"
  desc "Codex-authenticated OpenAI image generation CLI"
  homepage "https://github.com/niieani/imagegen"
  version "0.2.0"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "imagegen"

  on_macos do
    on_intel do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_darwin_amd64.tar.gz"
      sha256 "1e324929769bea58ea7a635bb141172ce637264597233227240389001c5b4460"
    end
    on_arm do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_darwin_arm64.tar.gz"
      sha256 "0356f1285da05e3206f5ed91c42f2bcae45432a5fecf6663940628bb009b8f46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_linux_amd64.tar.gz"
      sha256 "280d2f469e8f7f421b817512e22d7e84dfdef73c2abc502f2a15354566c74c71"
    end
    on_arm do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_linux_arm64.tar.gz"
      sha256 "1edc1b389a01eaa1479dbf587852a9f5b82b8e86f7cd8e4b3cf9a6db035e2460"
    end
  end
end
