# This file is generated by niieani/imagegen release automation. DO NOT EDIT.
cask "imagegen" do
  name "imagegen"
  desc "Codex-authenticated OpenAI image generation CLI"
  homepage "https://github.com/niieani/imagegen"
  version "0.1.0"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "imagegen"

  on_macos do
    on_intel do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_darwin_amd64.tar.gz"
      sha256 :no_check
    end
    on_arm do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_darwin_arm64.tar.gz"
      sha256 :no_check
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_linux_amd64.tar.gz"
      sha256 :no_check
    end
    on_arm do
      url "https://github.com/niieani/imagegen/releases/download/v#{version}/imagegen_#{version}_linux_arm64.tar.gz"
      sha256 :no_check
    end
  end
end
