# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "CLI to keep Git repositories consistent across machines."
  homepage "https://github.com/niieani/bb-project"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/niieani/bb-project/releases/download/v0.4.0/bb_0.4.0_darwin_amd64.tar.gz"
      sha256 "ec8ae34d3c5672091e9fc13710d9c7d6d332ab82558f1af39c89bd4348af9405"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/niieani/bb-project/releases/download/v0.4.0/bb_0.4.0_darwin_arm64.tar.gz"
      sha256 "f8691e8cac880c8f067b84f8326fcfd2d584fca0ba9de1e9b867350366ee13c0"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/niieani/bb-project/releases/download/v0.4.0/bb_0.4.0_linux_amd64.tar.gz"
      sha256 "774dc70f4b7a3f620ab84606d2f81a723e3024fc64cc2ded35ccdc8cad0341b1"
      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/niieani/bb-project/releases/download/v0.4.0/bb_0.4.0_linux_arm64.tar.gz"
      sha256 "2f510a0a5be05c995d9e463d3d31c7a3b4e8090e98d93551c25e7677106aca0b"
      def install
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "version"
  end
end
