# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "CLI to keep Git repositories consistent across machines."
  homepage "https://github.com/niieani/bb-project"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/niieani/bb-project/releases/download/v0.2.0/bb_0.2.0_darwin_amd64.tar.gz"
      sha256 "da556202de5e6f782bd8fd9b87fbe524c1e8676a639b0de8ed40441af2d2f03a"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/niieani/bb-project/releases/download/v0.2.0/bb_0.2.0_darwin_arm64.tar.gz"
      sha256 "6cde098d6d5704d6624faa191d827f67e39b8a620cca7c6355a80819a396914b"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/niieani/bb-project/releases/download/v0.2.0/bb_0.2.0_linux_amd64.tar.gz"
      sha256 "ed6061f8873dc635c999595f981427bc87b47dbc70f3b2468d8dafd9d8f0c995"
      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/niieani/bb-project/releases/download/v0.2.0/bb_0.2.0_linux_arm64.tar.gz"
      sha256 "97b8a6d43356051958d346fa103ac0d434e931f2044996b92b0692212748b3c0"
      def install
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "version"
  end
end
